services:
  - type: web
    name: replanta-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENAI_API_KEY
        sync: false
      - key: MEDIUM_TOKEN
        sync: false
      - key: IMGUR_CLIENT_ID
        sync: false
      - key: DEVTO_TOKEN
        sync: false
